import * as jwt from "jsonwebtoken";
import {environment} from "../environment";
import {AuthenticationError} from "apollo-server";

/**
 * The payload of every JWT token that is generated by this application.
 */
export interface JwtPayload {
  userId: number;
}

export function generateJwtToken(userId: number): string {
  return jwt.sign({userId} as JwtPayload, environment.SECRET, {expiresIn: '2 days'});
}

export function verifyToken(token: string | undefined): JwtPayload | undefined {
  if (!token) {
    return undefined;
  }
  try {
    // 'Bearer xyz' should become just 'xyz'.
    const bearerToken = token.slice(7);
    return jwt.verify(bearerToken, environment.SECRET) as JwtPayload;
  } catch (e) {
    throw new AuthenticationError('The Authorization Header of your request was set but could not be verified. It might be expired.')
  }
}
