name: lammes-assistant

static_sites:
- name: lammes-assistant-ionic-app
  github:
    repo: simon-lammes/lammes-assistant
    branch: master
    deploy_on_push: true
  source_dir: lammes-assistant-ionic-app
  dockerfile_path: lammes-assistant-ionic-app/Dockerfile
  output_dir: /app
  # Needed for SPA routing. When the user visits /anything, we want digitalocean to 
  # route to the index.html and let the Angular router handle the rest of the routing.
  catchall_document: index.html
  routes:
  - path: /site

services:
- name: lammes-assistant-apollo-server
  github:
    repo: simon-lammes/lammes-assistant
    branch: master
    deploy_on_push: true
  source_dir: lammes-assistant-apollo-server
  dockerfile_path: lammes-assistant-apollo-server/Dockerfile
  router:
    - /api
