# This file is easier to manage when you just copy the current value from the DigitalOcean App Platform console.
# You might ask why this file exists then. We use it to track changes to our App Platform instnace configuration.
# Furthermore, there are some aspects of app platform that cannot yet be managed in the UI but only with this file.
# An example is support for monorepos. This project is a monorepo so we needed to configure our App Plattform via 
# this file. Whenever you use this file to update the configuration, make sure this file contains the latest changes you made in
# the DigitalOcean UI. BTW, it is save to store encryped variables in this file. Those are prefixed with "EV[". Reference:
# https://www.digitalocean.com/community/questions/how-to-use-environment-values-of-type-secret-on-following-submissions
databases:
- cluster_name: app-36c1bd8a-2972-4e2e-843e-0f9f13c90834
  db_name: lammes_assistant_prod
  db_user: graphql-server
  engine: PG
  name: app-36c1bd8a-2972-4e2e-843e-0f9f
  production: true
  version: "12"
name: lammes-assistant
region: ams
services:
- dockerfile_path: lammes-assistant-apollo-server/Dockerfile
  envs:
  - key: SECRET
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:f2dsvfPBAXCNsFqmAORcilNhXBM9gQS8:LRBjnZueGMQ2QkD+PKSkvIHWiOsDsfwuYEBifMnYEnZtqrLni3DK0jAFDAQ5A2NX75In7K/Ym48QqCKr]
  - key: DATABASE_URL
    scope: RUN_TIME
    value: ${app-36c1bd8a-2972-4e2e-843e-0f9f.DATABASE_URL}
  - key: SPACES_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:yftFZtt7ajDPBceUYC4ZFXJMzIAStQM5:HdcXgqh8noEHCijpDnms2QAYQXiRz+tbx2VvYSelbkoWXqvr]
  - key: SPACES_SECRET
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:bhLwJ+8jgQALtDINAitP+obvDEDEOI86:inPr0co3g0B7ZDpLOg0z5vQ9yAFC49wfJIZ9hjKUVlxeU8A87bX+MLPQv1e+Rj5e2gfxksbONzNe/iw=]
  github:
    branch: master
    deploy_on_push: true
    repo: simon-lammes/lammes-assistant
  http_port: 4000
  instance_count: 1
  instance_size_slug: basic-xxs
  name: lammes-assistant-apollo-server
  routes:
  - path: /api
  source_dir: lammes-assistant-apollo-server
static_sites:
- catchall_document: index.html
  dockerfile_path: lammes-assistant-ionic-app/Dockerfile
  github:
    branch: master
    deploy_on_push: true
    repo: simon-lammes/lammes-assistant
  name: lammes-assistant-ionic-app
  output_dir: /app
  routes:
  - path: /
  source_dir: lammes-assistant-ionic-app